import 'package:flutter/material.dart';

final List<Map<String, dynamic>> features = [
  {
    "icon": Icons.school,
    "title": "AI-Powered Study Plan",
    "description": "Daily personalized study schedules generated by AI."
  },
  {
    "icon": Icons.book,
    "title": "AI-Generated Notes",
    "description": "Textbook summaries in an easy-to-understand format."
  },
  {
    "icon": Icons.memory,
    "title": "Memory Techniques",
    "description": "Mind maps, mnemonics & spaced repetition for retention."
  },
  {
    "icon": Icons.lightbulb,
    "title": "Instant Doubt Solver",
    "description": "24/7 AI-powered explanations & solutions."
  },
  {
    "icon": Icons.sports_esports,
    "title": "Distraction Control",
    "description": "Limits social media & gaming apps to boost focus."
  },
  {
    "icon": Icons.emoji_events,
    "title": "Gamification & Rewards",
    "description": "Earn XP, streaks & prizes to stay motivated."
  },
  {
    "icon": Icons.analytics,
    "title": "Smart Mock Tests",
    "description": "AI adjusts difficulty & detects weak areas."
  },
  {
    "icon": Icons.work,
    "title": "Career Guidance",
    "description": "AI suggests careers based on your strengths."
  },
  {
    "icon": Icons.code,
    "title": "Programming & AI Training",
    "description": "Learn Python, Java, AI, Data Science & more."
  },
];
